SELECT
t1.SK_ACTIVE_KEY,
t1.ID_RSSD,
COALESCE(t2.NM_LGL, t1.NM_LGL) AS NM_LGL,
COALESCE(t2.NM_SHORT, t1.NM_SHORT) AS NM_SHORT,
COALESCE(t2.ENTITY_TYPE, t1.ENTITY_TYPE)  AS ENTITY_TYPE,
COALESCE(t2.ACT_PRIM_CD, t1.ACT_PRIM_CD) AS ACT_PRIM_CD,
COALESCE(t2.CITY, t1.CITY) AS CITY,
COALESCE(t2.CNTRY_NM, t1.CNTRY_NM) AS CNTRY_NM,
COALESCE(t2.STATE_ABBR_NM, t1.STATE_ABBR_NM) AS STATE_ABBR_NM,
COALESCE(t2.ZIP_CD, t1.ZIP_CD) AS ZIP_CD,
COALESCE(t2.DOMESTIC_IND, t1.DOMESTIC_IND) AS DOMESTIC_IND,
COALESCE(t2.PRIM_FED_REG, t1.PRIM_FED_REG) AS PRIM_FED_REG,
IF(
  md5(concat(
    t1.NM_LGL, t1.NM_SHORT, t1.ENTITY_TYPE, t1.ACT_PRIM_CD, t1.CITY, t1.CNTRY_NM, t1.STATE_ABBR_NM, t1.ZIP_CD, t1.DOMESTIC_IND, t1.PRIM_FED_REG
  )) ==
  md5(concat(
    t2.NM_LGL, t2.NM_SHORT, t2.ENTITY_TYPE, t2.ACT_PRIM_CD, t2.CITY, t2.CNTRY_NM, t2.STATE_ABBR_NM, t2.ZIP_CD, t2.DOMESTIC_IND, t2.PRIM_FED_REG
  ))
  , t1.AUDIT_TIMESTAMP,CURRENT_TIMESTAMP
) AS AUDIT_TIMESTAMP
FROM (cos://us-south/grp-transform-anushka/DIM_ACTIVE.CSV STORED AS CSV) AS t1
LEFT JOIN (cos://us-south/grp-transform-anushka/DIM_ACTIVE_SOURCE STORED AS CSV) AS t2
ON t1.ID_RSSD = t2.ID_RSSD

INTO cos://us-south/grp-transform-anushka/DIM_ACTIVE_UPD JOBPREFIX NONE STORED AS CSV