SELECT DISTINCT
ID_RSSD, NM_LGL, NM_SHORT, ENTITY_TYPE, ACT_PRIM_CD, CITY, CNTRY_NM, STATE_ABBR_NM, ZIP_CD, DOMESTIC_IND, PRIM_FED_REG
FROM cos://us-south/grp-stage-anushka/ACTIVE_STAGE.CSV STORED AS CSV
order by ID_RSSD
limit 75

INTO cos://us-south/grp-transform-anushka/DIM_ACTIVE_SOURCE JOBPREFIX NONE STORED AS CSV